import streamlit as st

def process_journal_entry():
  with st.form(key='thought_checker'):
    default_journal_entry = "This is an example journal entry generated by ChatGPT.\nYou can edit it or paste your own entry here."

    journal_text = st.text_area("Journal entry:", value=default_journal_entry, height=300, max_chars=2000)

    # Form submission button
    submitted = st.form_submit_button('Submit')
    if submitted:
      st.write('You have submitted the following journal entry:')
      st.write(journal_text)


def thought_checker():
    st.title('🧠 Thought Checker')
    st.write('Enter a journal entry, and this program will auto-detect unhelpful thinking patterns (cognitive distortions) that are present in your entry, so you can focus on the more helpful reframing part.')
    process_journal_entry()
